name: Lint and check code
on: push
jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: Get repository
        uses: actions/checkout@v4
      - name: Run gitleaks
        uses: gitleaks/gitleaks-action@v2

  lint_and_validate_terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Get repository
        uses: actions/checkout@v4
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v4
      - name: Terraform init
        run: terraform init
      - name: Terraform fmt
        run: terraform fmt -check -recursive
      - name: Terraform validate
        run: terraform validate
